/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelInformationSystem;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import Data.DB;
import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Rahima
 */
public class HotelInformation extends javax.swing.JFrame {

    /**
     * Creates new form HotelInformation
     */
    public HotelInformation() {
        initComponents();
        this.setLocationRelativeTo(null);

        //Pk.setVisible(true);
        bUpdate.setEnabled(true);
        bDelete.setEnabled(true);
        bAdd.setEnabled(true);
        setListTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        bAdd = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladdinformation = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfRoomNo = new javax.swing.JTextField();
        tfRoomKey = new javax.swing.JTextField();
        tfRate = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbNationality = new javax.swing.JComboBox<>();
        labelID = new javax.swing.JLabel();
        cbBedType = new javax.swing.JComboBox<>();
        tfCheckInDate = new javax.swing.JTextField();
        tfDateOfOut = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfMobileNo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        blogout = new javax.swing.JButton();
        bSearch = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(37, 204, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true)));

        jLabel2.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel2.setText("FirstName");

        jLabel3.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel3.setText("LastName");

        jLabel4.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel4.setText("Address");

        tfFirstName.setBackground(new java.awt.Color(108, 122, 137));
        tfFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tfLastName.setBackground(new java.awt.Color(108, 122, 137));
        tfLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tfAddress.setBackground(new java.awt.Color(108, 122, 137));
        tfAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        bAdd.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Add.png"))); // NOI18N
        bAdd.setText("Add");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });

        bUpdate.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        bUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Update.png"))); // NOI18N
        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bDelete.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Delete 11.png"))); // NOI18N
        bDelete.setText("Delete");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        tbladdinformation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbladdinformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FirstName", "LastName", "Address", "Mobile No", "Nationality", "Gender", "CheckInDate", "DateOfOut", "Bed Type", "Room No", "Room Key", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbladdinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladdinformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbladdinformation);

        jLabel6.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel6.setText("Nationality");

        jLabel7.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel8.setText("Check In ");

        jLabel9.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel9.setText("Check Out");

        jLabel10.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel10.setText("Bed Type");

        jLabel11.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel11.setText("Room No");

        jLabel12.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel12.setText("Room Key");

        jLabel14.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel14.setText("Rate");

        tfRoomNo.setBackground(new java.awt.Color(108, 122, 137));
        tfRoomNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRoomNoActionPerformed(evt);
            }
        });

        tfRoomKey.setBackground(new java.awt.Color(108, 122, 137));
        tfRoomKey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfRoomKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRoomKeyActionPerformed(evt);
            }
        });

        tfRate.setBackground(new java.awt.Color(108, 122, 137));
        tfRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRateActionPerformed(evt);
            }
        });

        cbGender.setBackground(new java.awt.Color(108, 122, 137));
        cbGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female" }));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });

        cbNationality.setBackground(new java.awt.Color(108, 122, 137));
        cbNationality.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbNationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "British", "Scottish", "Norwegian", "Swiss", "Austrian", "French", "Filipino", "German", "Italian", "American", "Canadian", "Russian", "Greek", "Spanish", "Brazilian", "Australian", "New Zealander", "Egyptian", "Chinese", "Korean", "Japanese", "South African" }));
        cbNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNationalityActionPerformed(evt);
            }
        });

        cbBedType.setBackground(new java.awt.Color(108, 122, 137));
        cbBedType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbBedType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Bed", "Double Bed" }));
        cbBedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBedTypeActionPerformed(evt);
            }
        });

        tfCheckInDate.setBackground(new java.awt.Color(108, 122, 137));
        tfCheckInDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCheckInDateActionPerformed(evt);
            }
        });

        tfDateOfOut.setBackground(new java.awt.Color(108, 122, 137));
        tfDateOfOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfDateOfOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDateOfOutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 18)); // NOI18N
        jLabel13.setText("Mobile No");

        tfMobileNo.setBackground(new java.awt.Color(108, 122, 137));
        tfMobileNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileNoActionPerformed(evt);
            }
        });
        tfMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMobileNoKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(253, 114, 114));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel5.setText("HOTEL INFORMATION SYSTEM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Stitch.png"))); // NOI18N

        blogout.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Logout.png"))); // NOI18N
        blogout.setText("Logout");
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        bSearch.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        bSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Search 12.png"))); // NOI18N
        bSearch.setText("Search");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("      RH WINTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(blogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(bSearch)
                        .addGap(43, 43, 43)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bSearch)
                            .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Month  Day  Year");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Month  Day   Year");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(tfRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(tfCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(56, 56, 56))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(bUpdate)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfDateOfOut, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tfRoomKey, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(95, 95, 95)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel10))
                                                .addGap(64, 64, 64)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfRate, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbBedType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(bDelete))))
                            .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfDateOfOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbBedType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(tfCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRoomKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed

        if (labelID.getText().equals("")) {
            addList();
        } else {
            JOptionPane.showMessageDialog(null, "Wrong Information", "Error", JOptionPane.ERROR_MESSAGE);
        }

        setListTable();
        clearFields();
    }//GEN-LAST:event_bAddActionPerformed

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed

        if (labelID.getText().equals("")) {
            addList();
        } else {
            int id = Integer.parseInt(labelID.getText());
            updateList(id);
                    
        }

        setListTable();
        clearFields();
        bUpdate.setEnabled(true);
        bDelete.setEnabled(true);
        bAdd.setEnabled(true);
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed

        int id = Integer.parseInt(labelID.getText());
        deleteAct(id);
        clearFields();
        setListTable();
        bUpdate.setEnabled(true);
        bDelete.setEnabled(true);
        bAdd.setEnabled(true);
    }//GEN-LAST:event_bDeleteActionPerformed

    private void tbladdinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladdinformationMouseClicked

        int id = tbladdinformation.getSelectedRow();
        labelID.setText(tbladdinformation.getValueAt(id, 0).toString());
        tfFirstName.setText(tbladdinformation.getValueAt(id, 1).toString());
        tfLastName.setText(tbladdinformation.getValueAt(id, 2).toString());
        tfAddress.setText(tbladdinformation.getValueAt(id, 3).toString());
        tfMobileNo.setText(tbladdinformation.getValueAt(id, 4).toString());
        cbNationality.setSelectedItem(tbladdinformation.getValueAt(id, 5).toString());
        cbGender.setSelectedItem(tbladdinformation.getValueAt(id, 6).toString());
        tfCheckInDate.setText(tbladdinformation.getValueAt(id, 7).toString());
        tfDateOfOut.setText(tbladdinformation.getValueAt(id, 8).toString());
        cbBedType.setSelectedItem(tbladdinformation.getValueAt(id, 9).toString());
        tfRoomNo.setText(tbladdinformation.getValueAt(id, 10).toString());
        tfRoomKey.setText(tbladdinformation.getValueAt(id, 11).toString());
        tfRate.setText(tbladdinformation.getValueAt(id, 12).toString());

        // labelID.setVisible(true);
        bUpdate.setEnabled(true);
        bDelete.setEnabled(true);
        bAdd.setEnabled(true);

    }//GEN-LAST:event_tbladdinformationMouseClicked

    private void tfRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRoomNoActionPerformed

    private void tfRoomKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRoomKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRoomKeyActionPerformed

    private void tfRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRateActionPerformed

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed

    }//GEN-LAST:event_cbGenderActionPerformed

    private void cbNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNationalityActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        setListTable();
        clearFields();

    }//GEN-LAST:event_bSearchActionPerformed

    private void cbBedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBedTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBedTypeActionPerformed

    private void tfCheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCheckInDateActionPerformed

    private void tfDateOfOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDateOfOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDateOfOutActionPerformed

    private void tfMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileNoActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
      JOptionPane.showMessageDialog(null, "Do you really want to log out?","Log out", JOptionPane.CLOSED_OPTION);
         dispose();
         
         
    }//GEN-LAST:event_blogoutActionPerformed

    private void tfMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMobileNoKeyTyped
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(!(Character.isDigit(ch) || (ch == KeyEvent.VK_SPACE) || ch == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        if(tfMobileNo.getText().length() >= 11) {
            evt.consume();
        } else if (!Character.isDigit(ch)) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_tfMobileNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bUpdate;
    private javax.swing.JButton blogout;
    private javax.swing.JComboBox<String> cbBedType;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbNationality;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JTable tbladdinformation;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCheckInDate;
    private javax.swing.JTextField tfDateOfOut;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfMobileNo;
    private javax.swing.JTextField tfRate;
    private javax.swing.JTextField tfRoomKey;
    private javax.swing.JTextField tfRoomNo;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {

        tfFirstName.setText("");
        tfLastName.setText("");
        tfAddress.setText("");
        tfMobileNo.setText("");
        cbNationality.setSelectedItem("");
        cbGender.setSelectedItem("");
        tfCheckInDate.setText("");
        tfDateOfOut.setText("");
        cbBedType.setSelectedItem("");
        tfRoomNo.setText("");
        tfRoomKey.setText("");
        tfRate.setText("");

    }

    private void setListTable() {

        try {
            String s = tfSearch.getText();
            String[][] data = Activity.arraylistTo2dArray(Activity.searchActivityByName(s));
            String[] columnNames = {"id.", "FirstName", "LastName", "Address", "MobileNo", "Nationality", "Gender", "CheckInDate", "DateOfOut",
                "BedType", "RoomNo", "RoomKey", "Rate"};
            DefaultTableModel pro = new DefaultTableModel(data, columnNames);
            tbladdinformation.setModel(pro);
            TableColumnModel column = tbladdinformation.getColumnModel();
            tbladdinformation.setColumnModel(column);
        } catch (SQLException ex) {
            Logger.getLogger(HotelInformation.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void deleteAct(int id) {

        String q = "DELETE FROM `information` WHERE `information`.`id` = %d;";

        q = String.format(q, id);

        try {
            DB.Query(q, true);
            JOptionPane.showMessageDialog(null, "Successfully Information Deleted");
        } catch (SQLException ex) {
            Logger.getLogger(HotelInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        setListTable();
        clearFields();
    }

    private void updateList(int id) {

        String FirstName = tfFirstName.getText();
        String LastName = tfLastName.getText();
        String Address = tfAddress.getText();
        String MobileNo = tfMobileNo.getText();
        String Nationality = cbNationality.getSelectedItem().toString();
        String Gender = cbGender.getSelectedItem().toString();
        String CheckInDate = tfCheckInDate.getText();
        String DateOfOut = tfDateOfOut.getText();
        String BedType = cbBedType.getSelectedItem().toString();
        String RoomNo = tfRoomNo.getText();
        String RoomKey = tfRoomKey.getText();
        String Rate = tfRate.getText();

        String q = "UPDATE `information` SET `Firstname` = '%s',`Lastname` = '%s',"
                + "`Address` = '%s',`MobileNo` = '%s',`Nationality` = '%s',`Gender` = '%s',`CheckInDate` = '%s',`DateOfOut` = '%s'"
                + ",`BedType` = '%s',`RoomNo` = '%s',`RoomKey` = '%s',`Rate` = '%s'"
                + "WHERE `information`.`id` = '%d'";

        q = String.format(q, FirstName, LastName, Address, MobileNo, Nationality, Gender, CheckInDate, DateOfOut, BedType,
                RoomNo, RoomKey, Rate, id);

        try {
            DB.Query(q, true);
            JOptionPane.showMessageDialog(null, "Successfully Information Updated");
        } catch (SQLException ex) {
            Logger.getLogger(HotelInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        setListTable();

    }

    private void addList() {

        String FirstName = tfFirstName.getText();
        String LastName = tfLastName.getText();
        String Address = tfAddress.getText();
        String MobileNo = tfMobileNo.getText();
        String Nationality = cbNationality.getSelectedItem().toString();
        String Gender = cbGender.getSelectedItem().toString();
        String CheckInDate = tfCheckInDate.getText();
        String DateOfOut = tfDateOfOut.getText();
        String BedType = cbBedType.getSelectedItem().toString();
        String RoomNo = tfRoomNo.getText();
        String RoomKey = tfRoomKey.getText();
        String Rate = tfRate.getText();
       
        String q = "INSERT INTO `information` (`id`, `Firstname`, `Lastname`, `Address`, `MobileNo`, `Nationality`, `Gender`, `CheckInDate`, `DateOfOut`, `BedType`, `RoomNo`, `RoomKey`, `Rate`) "
                + "VALUES (NULL, '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')";
             

        q = String.format(q, FirstName, LastName, Address, MobileNo, Nationality, Gender, CheckInDate, DateOfOut, BedType,
                RoomNo, RoomKey, Rate);

        try {
            DB.Query(q, true);
            JOptionPane.showMessageDialog(null, "Successfully Information Added");
        } catch (SQLException ex) {
            Logger.getLogger(HotelInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
        setListTable();

    }

    private void systemExit() {

    }

}
